language: node_js
node_js:
 - 4.1
sudo: false
before_install:
 - rvm install 2.2.4
install:
 - bundle install
 - npm install -g firebase-tools
script:
 - bundle exec jekyll build
 - firebase deploy --token ${FirebaseToken}