language: ruby
sudo: false
rvm:
 - 2.2
before_install:
 - nvm install 4.1
install:
 - bundle install
 - npm install
 - npm install -g firebase-tools
script:
 - npm run lint
 - npm run build
after_success:
 - firebase deploy --token "${FIREBASE_TOKEN}"